#!/bin/sh

[ "$BUTTON" = "reboot" ] || exit 0
[ "$ACTION" = "pressed" ] || exit 0

# Prevent repeated shutdown events
[ -e /tmp/ix4-shutdown ] && exit 0
touch /tmp/ix4-shutdown

logger -t ix4-button "Power button pressed, shutting down"

# Show shutdown message on LCD
/usr/bin/ix4lcd "                                        The system shuts down; you can turn off the power once all the LEDs have gone out."

# Turn off white power LED
LED="/sys/class/leds/white:power"
echo none > "$LED/trigger"
echo 0 > "$LED/brightness"

# Give LCD and LED time to update
sleep 2

/sbin/poweroff
