#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service()
{
    /usr/bin/ix4lcd --clear

    echo 0 > /tmp/ix4lcd-page

    /usr/bin/ix4lcd --log --page 0
}

stop_service()
{
    /usr/bin/ix4lcd --clear
}
